---
- hosts: localhost
  connection: local
  vars:

    home_dir: "/Users/{{user_name}}"
    brew_dir: /usr/local

    casks:
      - google-chrome
      - firefox
    sudo_casks:
      - virtualbox
      - java6
      - java7
    kegs:
      - maven31
    homebrew_paths:
      - "{{brew_dir}}"
      - "{{brew_dir}}/Cellar"
      - "{{brew_dir}}/Library"
      - /Library/Caches/Homebrew
      - /Library/Caches/Homebrew/Formula
      - /opt/homebrew-cask

  tasks:

  - name: Gather mac facts
    action: mac_facts
  
  - name: install kegs with brew
    homebrew: name={{item}} state=present
    with_items: kegs

  - name: install casks with brew
    homebrew_cask: name={{item}} state=present
    with_items: casks

