---
- hosts: localhost
  connection: local
  vars:

    home_dir: "/Users/{{user_name}}"
    brew_dir: /usr/local

    rtc_args: https://docs.google.com/uc?export=download&id=0B6ViKrNN-Ja6dGEzRUdSeDk2ZVk ~/Downloads/jazz.zip

    casks: # .dmg, .app, .zip type applications via brew-cask
      - google-chrome
      - firefox
      - intellij-idea
    sudo_casks:
      - virtualbox
      - java6
      - java7
    kegs:
      - maven31
    homebrew_paths:
      - "{{brew_dir}}"
      - "{{brew_dir}}/Cellar"
      - "{{brew_dir}}/Library"
      - /Library/Caches/Homebrew
      - /Library/Caches/Homebrew/Formula
      - /opt/homebrew-cask

  tasks:

  - name: Gather mac facts
    action: mac_facts

  - name: Copy temporary scripts
    copy: src=scripts/ dest=/tmp/ansible_temp_scripts owner={{user_name}} mode=0777

  - name: Copying the RTC Client
    script: grab_jazz
